export enum REPORT_TIMEOUT_ACTION_KEY {
  'NONE' = 'NONE',

  // new user creat address program
  'CLICK_CREATE_NEW_ADDRESS' = 'CLICK_CREATE_NEW_ADDRESS',
  'SET_PASSWORD_DONE' = 'SET_PASSWORD_DONE',
  'CLICK_ICLOUD_BACKUP' = 'CLICK_ICLOUD_BACKUP',
  'CLICK_MANUAL_BACKUP' = 'CLICK_MANUAL_BACKUP',
  'ADD_NEW_ADDRESS_DONE' = 'ADD_NEW_ADDRESS_DONE',
  // 'ICLOUD_BACKUP_DONE' = 'ICLOUD_BACKUP_DONE',
  // 'MANUAL_BACKUP_DONE' = 'MANUAL_BACKUP_DONE',

  // new user import address program
  'CLICK_HAVE_ADDRESS' = 'CLICK_HAVE_ADDRESS',
  'CLICK_IMPORT_SEED_PHRASE' = 'CLICK_IMPORT_SEED_PHRASE',
  'IMPORT_SEED_PHRASE_CONFIRM' = 'IMPORT_SEED_PHRASE_CONFIRM',
  // 'SET_PASSWORD_DONE' = 'SET_PASSWORD_DONE',
  // 'IMPORT_SEED_PHRASE_SET_PASSWORD' = 'IMPORT_SEED_PHRASE_SET_PASSWORD',
  // 'IMPORT_SEED_PHRASE_DONE' = 'IMPORT_SEED_PHRASE_DONE',
  'IMPORT_SEED_PHRASE_RESTORE_CONFIRM' = 'IMPORT_SEED_PHRASE_RESTORE_CONFIRM',
  // 'IMPORT_SEED_PHRASE_RESTORE_PASSWORD' = 'IMPORT_SEED_PHRASE_RESTORE_PASSWORD',
  // 'IMPORT_SEED_PHRASE_RESTORE_DONE' = 'IMPORT_SEED_PHRASE_RESTORE_DONE',
  'CLICK_IMPORT_PRIVATE_KEY' = 'CLICK_IMPORT_PRIVATE_KEY',
  'IMPORT_PRIVATE_KEY_CONFIRM' = 'IMPORT_PRIVATE_KEY_CONFIRM',
  // 'SET_PASSWORD_DONE' = 'SET_PASSWORD_DONE',
  // 'IMPORT_PRIVATE_KEY_SET_PASSWORD' = 'IMPORT_PRIVATE_KEY_SET_PASSWORD',
  // 'IMPORT_PRIVATE_KEY_DONE' = 'IMPORT_PRIVATE_KEY_DONE',
  'CLICK_CONNECT_HARDWARE' = 'CLICK_CONNECT_HARDWARE',
  'CLICK_LEDGER_CONNECT' = 'CLICK_LEDGER_CONNECT',
  // 'LEDGER_CONNECT_DONE' = 'LEDGER_CONNECT_DONE',

  // user sync extension address program
  'CLICK_SCAN_SYNC_EXTENSION' = 'CLICK_SCAN_SYNC_EXTENSION',
  'SCAN_SYNC_EXTENSION_SHOW_PASSWORD' = 'SCAN_SYNC_EXTENSION_SHOW_PASSWORD',
  'SCAN_SYNC_EXTENSION_CONFIRM' = 'SCAN_SYNC_EXTENSION_CONFIRM',
  'SCAN_SYNC_EXTENSION_DONE' = 'SCAN_SYNC_EXTENSION_DONE',

  // user swap action timeout
  'CLICK_GO_SWAP_SERVICE' = 'CLICK_SWAP_SERVICE',
  'CLICK_SWAP_OR_APPROVE_BTN' = 'CLICK_SWAP_OR_APPROVE_BTN',
  'CLICK_SWAP_TO_SIGN' = 'CLICK_SWAP_TO_SIGN',
  'CLICK_SWAP_TO_CONFIRM' = 'CLICK_SWAP_TO_CONFIRM',
  'SWAP_ACTION_HAVE_DONE' = 'SWAP_ACTION_HAVE_DONE',
}
