import EventEmitter from 'events';

export const eventBus: EventEmitter = new EventEmitter();

export const SIGN_HELPER_EVENTS = {
  broadcastToUI: 'broadcastToUI',
  broadcastToBackground: 'broadcastToBackground',
  TX_COMPLETED: 'TX_COMPLETED',
  SIGN_FINISHED: 'SIGN_FINISHED',
  TX_SUBMITTING: 'TX_SUBMITTING',
  WALLETCONNECT: {
    STATUS_CHANGED: 'WALLETCONNECT_STATUS_CHANGED',
    SESSION_STATUS_CHANGED: 'SESSION_STATUS_CHANGED',
    SESSION_ACCOUNT_CHANGED: 'SESSION_ACCOUNT_CHANGED',
    SESSION_NETWORK_DELAY: 'SESSION_NETWORK_DELAY',
    INIT: 'WALLETCONNECT_INIT',
    INITED: 'WALLETCONNECT_INITED',
    TRANSPORT_ERROR: 'TRANSPORT_ERROR',
    SCAN_ACCOUNT: 'SCAN_ACCOUNT',
  },
  GNOSIS: {
    TX_BUILT: 'TransactionBuilt',
    TX_CONFIRMED: 'TransactionConfirmed',
  },
  QRHARDWARE: {
    ACQUIRE_MEMSTORE_SUCCEED: 'ACQUIRE_MEMSTORE_SUCCEED',
  },
  LEDGER: {
    REJECTED: 'LEDGER_REJECTED',
    REJECT_APPROVAL: 'LEDGER_REJECT_APPROVAL',
  },
  ONEKEY: {
    REQUEST_PIN: 'ONEKEY_REQUEST_PIN',
    REQUEST_PASSPHRASE: 'ONEKEY_REQUEST_PASSPHRASE',
    CLOSE_UI_WINDOW: 'ONEKEY_CLOSE_UI_WINDOW',
  },
  COMMON_HARDWARE: {
    REJECTED: 'COMMON_HARDWARE_REJECTED',
  },
  LOCK_WALLET: 'LOCK_WALLET',
  RELOAD_TX: 'RELOAD_TX',

  PURCHASE_UPDATED: 'PURCHASE_UPDATED',

  AUTO_LOGIN_GAS_ACCOUNT: 'AUTO_LOGIN_GAS_ACCOUNT',

  PERPS: {
    LOG_OUT: 'PERPS_LOG_OUT',
    ADD_ADDRESSES: 'PERPS_ADD_ADDRESSES',
  },

  INNER_HISTORY_ITEM_COMPLETE: 'INNER_HISTORY_ITEM_COMPLETE',
} as const;
