import type { Chain } from '@debank/common';
import { SupportedChain } from '@rabby-wallet/rabby-api/dist/types';

const intToHex = (n: number) => {
  if (n % 1 !== 0) {
    throw new Error(`${n} is not int`);
  }
  return `0x${n.toString(16)}`;
};

export function supportedChainToChain(item: SupportedChain): Chain {
  const chainServerIdEnumDict = {
    eth: 'ETH',
    bsc: 'BSC',
    xdai: 'GNOSIS',
    matic: 'POLYGON',
    ftm: 'FTM',
    okt: 'OKT',
    heco: 'HECO',
    avax: 'AVAX',
    arb: 'ARBITRUM',
    op: 'OP',
    celo: 'CELO',
    movr: 'MOVR',
    cro: 'CRO',
    boba: 'BOBA',
    metis: 'METIS',
    btt: 'BTT',
    aurora: 'AURORA',
    mobm: 'MOBM',
    sbch: 'SBCH',
    hmy: 'HMY',
    fuse: 'FUSE',
    astar: 'ASTAR',
    klay: 'KLAY',
    rsk: 'RSK',
    iotx: 'IOTX',
    kcc: 'KCC',
    wan: 'WAN',
    sgb: 'SGB',
    evmos: 'EVMOS',
    dfk: 'DFK',
    tlos: 'TLOS',
    nova: 'NOVA',
    canto: 'CANTO',
    doge: 'DOGE',
    step: 'STEP',
    kava: 'KAVA',
    mada: 'MADA',
    cfx: 'CFX',
    brise: 'BRISE',
    ckb: 'CKB',
    tomb: 'TOMB',
    pze: 'PZE',
    era: 'ERA',
    eos: 'EOS',
    core: 'CORE',
    flr: 'FLR',
    wemix: 'WEMIX',
    mtr: 'METER',
    etc: 'ETC',
    fsn: 'FSN',
    pls: 'PULSE',
    rose: 'ROSE',
    ron: 'RONIN',
    oas: 'OAS',
    zora: 'ZORA',
    linea: 'LINEA',
    base: 'BASE',
    mnt: 'MANTLE',
    tenet: 'TENET',
    lyx: 'LYX',
    opbnb: 'OPBNB',
    loot: 'LOOT',
    shib: 'SHIB',
    manta: 'MANTA',
    scrl: 'SCRL',
    fx: 'FX',
    beam: 'BEAM',
    pego: 'PEGO',
    zkfair: 'ZKFAIR',
    fon: 'FON',
    bfc: 'BFC',
    alot: 'ALOT',
    xai: 'XAI',
    zeta: 'ZETA',
    rari: 'RARI',
    hubble: 'HUBBLE',
    mode: 'MODE',
    merlin: 'MERLIN',
    dym: 'DYM',
    eon: 'EON',
    blast: 'BLAST',
    sx: 'SX',
    platon: 'PLATON',
    map: 'MAP',
    frax: 'FRAX',
    aze: 'AZE',
    karak: 'KARAK',
  };
  return {
    id: item.community_id,
    enum: chainServerIdEnumDict[item.id] || item.id.toUpperCase(),
    name: item.name,
    serverId: item.id,
    hex: intToHex(item.community_id),
    network: item.community_id + '',
    nativeTokenSymbol: item.native_token?.symbol,
    nativeTokenLogo: item.native_token?.logo,
    nativeTokenDecimals: item.native_token?.decimals,
    nativeTokenAddress: item.native_token?.id,
    needEstimateGas: item.need_estimate_gas,
    scanLink: `${item.explorer_host}/${
      item.id === 'heco' ? 'transaction' : 'tx'
    }/_s_`,
    logo: item.logo_url,
    whiteLogo: item.white_logo_url,
    eip: {
      '1559': item.eip_1559,
    },
    severity: item.severity,
  };
}
